<a href="https://colab.research.google.com/github/R0ckie/Laboratory-6/blob/main/LinAlg_Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 1**

In [35]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline



In [36]:
B = np.array([ 
              [1,2,3,4,5],
              [6,7,8,9,10],
              [2,4,6,8,10],
              [1,3,5,6,9],
              [4,5,6,7,2]    
])

K = np.eye(5)

def describe_mat(matrix):
  if matrix.size > 0:
    zeroes = (B==0).all()
    ones = (B==1).all()
    Id = np.all(np.equal(B,K))
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\nIs zero identity: {zeroes}\nIs ones identity: {ones}\nIs Identity Matrix: {Id}')
    
  else: 
    print("Null identity") 

describe_mat(B)



Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2  4  6  8 10]
 [ 1  3  5  6  9]
 [ 4  5  6  7  2]]

Shape:	(5, 5)
Rank:	2
Is Square: True
Is zero identity: False
Is ones identity: False
Is Identity Matrix: False


**Task 2**

In [37]:
import numpy as np

L = np.array([[1,2,3],
              [3,4,5],
              [6,7,8],
              [5,4,7]])
E = 1
A = np.array([[5,6,4],
              [7,8,9],
              [1,2,3]])
N = 2
B = np.array([[8,9,1],
              [4,5,2],
              [5,9,3]])


def mat_operations(matrix1, matrix2):
    if np.isscalar(matrix1) == True and np.isscalar(matrix2) == True:
        print(matrix1, '--> scalar')
        print(matrix2, '--> scalar')
        print('********************************************************')

    elif np.isscalar(matrix2) == True:
        print(matrix2, 'Is a scalar')
        if matrix1.size > 0:
            is_square = True if matrix1.shape[0] == matrix1.shape[1] else False
            print(f'Matrix:\n{matrix1}\n\nShape:\t{matrix1.shape}\nRank:\t{matrix1.ndim}\nIs Square: {is_square}')
        else:
            print('Matrix is Null')
        print('********************************************************')

    elif np.isscalar(matrix1) == True:
        print(matrix1, 'Is a scalar')
        if matrix2.size > 0:
            is_square = True if matrix2.shape[0] == matrix2.shape[1] else False
            print(f'Matrix:\n{matrix2}\n\nShape:\t{matrix2.shape}\nRank:\t{matrix2.ndim}\nIs Square: {is_square}')
        else:
            print('Matrix is Null')
        print('********************************************************')
        
    elif np.isscalar(matrix1) == False and np.isscalar(matrix2) == False:
        if matrix1.size > 0 and matrix2.size > 0:
            is_square = True if matrix1.shape[0] == matrix1.shape[1] else False
            print(f'Matrix:\n{matrix1}\n\nShape:\t{matrix1.shape}\nRank:\t{matrix1.ndim}\nIs Square: {is_square}')
            print('********************************************************')
            is_square = True if matrix2.shape[0] == matrix2.shape[1] else False
            print(f'Matrix:\n{matrix2}\n\nShape:\t{matrix2.shape}\nRank:\t{matrix2.ndim}\nIs Square: {is_square}')
            print('********************************************************')
        else:
            print('Matrix is Null')

    if np.isscalar(matrix2) == True:
        sum = matrix1 + matrix2
        difference = matrix1 - matrix2
        product = matrix1 * matrix2
        quotient = matrix1 // matrix2
        print(sum)
        print(difference)
        print(product)
        print(quotient)

    elif np.isscalar(matrix1) == True:
        sum = matrix1 + matrix2
        difference = matrix1 - matrix2
        product = matrix1 * matrix2
        quotient = matrix1 // matrix2
        print(sum)
        print(difference)
        print(product)
        print(quotient)

    elif matrix1.shape == matrix2.shape:
        sum = matrix1 + matrix2
        difference = matrix1 - matrix2
        product = matrix1 * matrix2
        quotient = matrix1 // matrix2
        print(sum)
        print(difference)
        print(product)
        print(quotient) 
   

    else:
        print("Matrix is not equal in shape...")

mat_operations(L,A)
print('********************************************************')
mat_operations(A,B)
print('********************************************************')
mat_operations(A,N)
print('********************************************************')
mat_operations(E,N)

Matrix:
[[1 2 3]
 [3 4 5]
 [6 7 8]
 [5 4 7]]

Shape:	(4, 3)
Rank:	2
Is Square: False
********************************************************
Matrix:
[[5 6 4]
 [7 8 9]
 [1 2 3]]

Shape:	(3, 3)
Rank:	2
Is Square: True
********************************************************
Matrix is not equal in shape...
********************************************************
Matrix:
[[5 6 4]
 [7 8 9]
 [1 2 3]]

Shape:	(3, 3)
Rank:	2
Is Square: True
********************************************************
Matrix:
[[8 9 1]
 [4 5 2]
 [5 9 3]]

Shape:	(3, 3)
Rank:	2
Is Square: True
********************************************************
[[13 15  5]
 [11 13 11]
 [ 6 11  6]]
[[-3 -3  3]
 [ 3  3  7]
 [-4 -7  0]]
[[40 54  4]
 [28 40 18]
 [ 5 18  9]]
[[0 0 4]
 [1 1 4]
 [0 0 1]]
********************************************************
2 Is a scalar
Matrix:
[[5 6 4]
 [7 8 9]
 [1 2 3]]

Shape:	(3, 3)
Rank:	2
Is Square: True
********************************************************
[[ 7  8  6]
 [ 9 10 11]
 [ 3  4